name: Run tests and linter for all branches
on:
  push:
    tags-ignore:
      - '**'
    branches:
      - '**'

jobs:
  golangci-linter:
    name: Run golangci linter
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      - uses: runs-on/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Setup Go ✨
        uses: actions/setup-go@v4
        with:
          cache: false
          go-version-file: go.mod
      - name: Downloading dependencies
        shell: bash
        run: go mod download
      - uses: golangci/golangci-lint-action@v8
        name: run the linters
        with:
          skip-cache: true
          args: --timeout=10m
          version: v2.1.6
